[doctest] fix errors in yt.funcs docstrings
yt-project/yt pull request #2899
Opened 2020-09-12 13:52 UTC by neutrinoceros

## PR Summary
same as #2898, for `yt/funcs.py`

2020-09-12 20:07 UTC, matthewturk requested changes

2020-09-12 20:07 UTC, matthewturk commented on yt/utilities/lib/misc_utilities.pyx
> +        print(vxg.units, vyg.units, vzg.units)
hmmm...

2020-09-12 20:12 UTC, neutrinoceros commented on yt/utilities/lib/misc_utilities.pyx
> +        print(vxg.units, vyg.units, vzg.units)
oops

2020-09-14 20:01 UTC, munkm approved these changes

2020-09-14 20:27 UTC, neutrinoceros commented
@matthewturk could you review this again please :)

2020-09-14 20:27 UTC, matthewturk approved these changes

2020-09-14 20:33 UTC, merged