DOC: add an exhaustive list of deprecations to the yt4differences page
yt-project/yt pull request #3665
Opened 2021-11-12 11:05 UTC by neutrinoceros

## PR Summary

Fix #3451
This should be backported to the 4.0.x branch

2021-11-12 14:24 UTC, matthewturk submitted a review, later dismissed

2021-11-12 15:58 UTC, Xarthisius requested changes

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * :meth:`~yt.visualization.plot_container.PlotWindow.set_window_size` is deprecated
```suggestion
 * :meth:`~yt.visualization.plot_window.PlotWindow.set_window_size` is deprecated
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> +   favour to :meth:`~yt.visualization.plot_window.PWViewerMPL.clear_annotaions`
```suggestion
   favour to :meth:`~yt.visualization.plot_window.PWViewerMPL.clear_annotations`
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * :meth:`ImagePlotContainer.set_cbar_minorticks` is a deprecated alias for :meth:`ImagePlotContainer.set_colorbar_minorticks`
```suggestion
 * :meth:`~yt.visualization.plot_container.ImagePlotContainer.set_cbar_minorticks` is a deprecated alias for :meth:`~yt.visualization.plot_container.ImagePlotContainer.set_colorbar_minorticks`
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> +   ``Dataset.force_periodicity()`` if you need to force periodicity to ``True`` or ``False`` along all axes.
```suggestion
   :meth:`~yt.data_objects.static_output.Dataset.force_periodicity` if you need to force periodicity to ``True`` or ``False`` along all axes.
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * manually updating the ``periodicity`` attributed of a ``Dataset`` object is deprecated. Use the
```suggestion
 * manually updating the ``periodicity`` attributed of a :class:`~yt.data_objects.static_output.Dataset` object is deprecated. Use the
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``Dataset.add_smoothed_particle_field`` method is deprecated and already has no effect in yt 4.0 .
```suggestion
 * the :meth:`~yt.data_objects.static_output.Dataset.add_smoothed_particle_field` method is deprecated and already has no effect in yt 4.0 .
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``Dataset.add_gradient_fields`` used to accept an ``input_field`` keyword argument, now deprecated
```suggestion
 * the :meth:`~yt.data_objects.static_output.Dataset.add_gradient_fields` used to accept an ``input_field`` keyword argument, now deprecated
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * ``DatasetSeries.from_filenames()`` is deprecated because its functionality is now
```suggestion
 * :meth:`~yt.data_objects.time_series.DatasetSeries.from_filenames` is deprecated because its functionality is now
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> +   included in the basic ``__init__`` method. Use ``DatasetSeries()`` directly.
```suggestion
   included in the basic ``__init__`` method. Use :class:`~yt.data_objects.time_series.DatasetSeries` directly.
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``limits`` argument from :meth:`yt.visualization.image_writer.write_projection` is deprecated in
```suggestion
 * the ``limits`` argument from :meth:`~yt.visualization.image_writer.write_projection` is deprecated in
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``YTOutputNotIdentified`` error is a deprecated alias for ``YTUnidentifiedDataType``
```suggestion
 * the :class:`~yt.utilities.exceptions.YTOutputNotIdentified` error is a deprecated alias for :class:`~yt.utilities.exceptions.YTUnidentifiedDataType`
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``particle_type`` keyword argument from ``add_field`` methods is now a deprecated in favour to
```suggestion
 * the ``particle_type`` keyword argument from ``yt.add_field()`` (:meth:`~yt.fields.field_info_container.FieldInfoContainer.add_field`) and ``ds.add_field()`` (:meth:`~yt.data_objects.static_output.Dataset.add_field`) methods is now a deprecated in favor to
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``add_volume_weighted_smoothed_field`` is deprecated and already has no effect in yt 4.0 .
```suggestion
 * the :meth:`~yt.fields.particle_fields.add_volume_weighted_smoothed_field` is deprecated and already has no effect in yt 4.0 .
```

2021-11-12 15:58 UTC, Xarthisius commented on doc/source/yt4differences.rst
> + * the ``AMRKDTree.locate_brick`` method is deprecated in favour to, and is now an alias for ``AMRKDTree.locate_node``
```suggestion
 * the :meth:`~yt.utilities.amr_kdtree.amr_kdtree.AMRKDTree.locate_brick` method is deprecated in favor to, and is now an alias for :meth:`~yt.utilities.amr_kdtree.amr_kdtree.AMRKDTree.locate_node`
```

2021-11-12 16:00 UTC, chummels submitted a review, later dismissed
This is terrific!  Thank you for doing this, @neutrinoceros !

2021-11-12 16:00 UTC, chummels commented on doc/source/yt4differences.rst
> +   favour to :meth:`~yt.visualization.plot_window.PWViewerMPL.clear_annotaions`
```suggestion
   favour to :meth:`~yt.visualization.plot_window.PWViewerMPL.clear_annotations`
```

2021-11-12 16:14 UTC, neutrinoceros commented on doc/source/yt4differences.rst
> + * :meth:`~yt.visualization.plot_container.PlotWindow.set_window_size` is deprecated
nice catch !

2021-11-12 16:21 UTC, neutrinoceros commented
Thanks a lot @Xarthisius for your numerous corrections, it's much better now !

2021-11-12 17:10 UTC, neutrinoceros commented
(@matthewturk here again, auto-merge won't work for docs-only PRs)

2021-11-12 17:28 UTC, Xarthisius approved these changes

2021-11-15 10:29 UTC, matthewturk approved these changes
Looks good to me.  Merge whenever it's green, I say.

2021-11-15 10:32 UTC, neutrinoceros commented
it _is_ green already :)
It's only shown as "🟡" because auto-merge is waiting for the answer test job, which will not trigger because it's a doc-only patch

2021-11-15 10:33 UTC, neutrinoceros commented
Seems like I can't even regular-merge while auto-merge is setup this way

2021-11-15 10:36 UTC, merged